// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-children.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_children_default = defineTool({
  name: "list_children",
  title: "List children",
  description: "List the signed-in parent's child profiles (name, age group, triggers, calming preferences).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("child_profiles").select("id, name, age_group, known_triggers, calming_preferences, created_at").order("created_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { children: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-incidents.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_incidents_default = defineTool2({
  name: "list_incidents",
  title: "List recent incidents",
  description: "List recent SOS incidents for the signed-in parent, optionally filtered by child or problem category.",
  inputSchema: {
    child_id: z.string().uuid().nullable().describe("Filter to a specific child. Pass null for all children."),
    problem_category: z.string().nullable().describe("Filter to a specific problem category (e.g. bedtime_resistance). Pass null for all."),
    limit: z.number().int().min(1).max(50).describe("Maximum incidents to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ child_id, problem_category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("incidents").select("id, child_id, problem_category, note_text, summary_text, created_at").order("created_at", { ascending: false }).limit(limit);
    if (child_id) q = q.eq("child_id", child_id);
    if (problem_category) q = q.eq("problem_category", problem_category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { incidents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-incident.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_incident_default = defineTool3({
  name: "get_incident",
  title: "Get incident details",
  description: "Fetch a single incident with its coaching suggestions and any parent feedback.",
  inputSchema: {
    incident_id: z2.string().uuid().describe("The incident's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ incident_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data: incident, error } = await sb.from("incidents").select("id, child_id, problem_category, note_text, summary_text, created_at").eq("id", incident_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!incident) return { content: [{ type: "text", text: "Incident not found" }], isError: true };
    const [{ data: suggestions }, { data: feedback }] = await Promise.all([
      sb.from("incident_suggestions").select("position, title, reason, script, source_type").eq("incident_id", incident_id).order("position"),
      sb.from("incident_feedback").select("outcome, note, created_at").eq("incident_id", incident_id).maybeSingle()
    ]);
    const payload = { incident, suggestions: suggestions ?? [], feedback: feedback ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gymzdcweqkqbibeihdsn";
var mcp_default = defineMcp({
  name: "parentpilot-mcp",
  title: "ParentPilot",
  version: "0.1.0",
  instructions: "Tools for a ParentPilot parent. Use list_children to see the parent's kids, list_incidents to browse recent SOS sessions, and get_incident for the coaching suggestions and feedback on a specific incident. All tools are read-only and scoped to the signed-in parent.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_children_default, list_incidents_default, get_incident_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
